In [94]:
import pandas as pd
import numpy as np
import re

In [95]:
data = pd.read_csv('Michelin_Details.csv', index_col = 0)

In [96]:
df = data[data['country_alpha2'] == 'US'].copy()
df.reset_index(drop = True, inplace = True)
df.shape

(206, 23)

In [97]:
df['coast'] = pd.cut(df.lon, 2, labels=False)

# Find Restaurant by Subregion:

In [98]:
def has_num(text):
    if re.search(r'[\d]+', text) != None:
        return True
    return False

def has_apt(text):
    if re.search(r'Ste.|Unit', text) != None:
        return True
    return False

In [99]:
re.search(r'[\d]*', 'does this work 1234?')

In [100]:
split_address = df['address'].apply(lambda x: x.split(','))
split_address

0      [16573 Ventura Blvd.,  Encino,  91436,  United...
1      [1320 E. 7th St.,  Ste. 126,  Los Angeles,  90...
2      [132 The Embarcadero,  San Francisco,  94101, ...
3                      [5600 CA-1,  Elk,  United States]
4      [5200 Grand Del Mar Way,  San Diego,  92130,  ...
                             ...
201    [123 N. Jefferson St.,  Chicago,  60661,  Unit...
202    [2419 W. 14th St.,  Chicago,  60618,  United S...
203    [1466 N. Ashland Ave.,  Chicago,  60662,  Unit...
204    [2610 N. Cannon Dr.,  Chicago,  60614,  United...
205    [933 N. Ashland Ave.,  Chicago,  60622,  Unite...
Name: address, Length: 206, dtype: object

In [101]:
cities = []
for address in split_address:
    temp = address[1]
    if has_apt(temp):
        cities.append(address[2].strip())
    else:
        cities.append(temp.strip())
        
set(cities)

{'Beverly Hills',
 'Brooklyn',
 'Burlingame',
 'Carmel',
 'Chicago',
 'Costa Mesa',
 'Culver City',
 'Elk',
 'Encino',
 'Forestville',
 'Healdsburg',
 'Hollywood',
 'Long Island City',
 'Los Angeles',
 'Los Gatos',
 'Menlo Park',
 'Mountain View',
 'Napa',
 'New York',
 'Oakland',
 'Palo Alto',
 'Rutherford',
 'Sacramento',
 'San Anselmo',
 'San Diego',
 'San Francisco',
 'San Mateo',
 'Santa Monica',
 'Saratoga',
 'St. Helena',
 'Tarrytown',
 'Temple City',
 'Washington',
 'West Los Angeles',
 'Woodside',
 'Yountville'}

In [107]:
df['city'] = cities

# Sub-region

In [108]:
ca_list = df[df['coast'] == 0]
ca_split = pd.cut(ca_list['lat'], bins = 2, labels = ['SC', 'NC'])

In [109]:
ea_list = df[df['coast'] == 1]
ea_split = pd.cut(ea_list.lon, bins = [-90, -80, -75, 0], labels = ['CHI', 'DC', 'NY'])

In [110]:
pd.set_option('display.max_rows', 200)

ea_list[['address', 'lon']]

                                               address        lon
88     458 W. 17th St., New York, 10011, United States -74.006330
89     212 Greene Ave., Brooklyn, 11238, United States -73.962976
90       9 W. 53rd St., New York, 10019, United States -73.976280
91       295 Grand St., New York, 11211, United States -73.957500
92     73 Thompson St., New York, 10012, United States -74.003006
93      89 E. 42nd St., New York, 10017, United States -73.977864
94     11 Madison Ave., New York, 10010, United States -73.987120
95   47 E. Houston St., New York, 10012, United States -73.994800
96      381 Lenox Ave., New York, 10027, United States -73.943726
97   72 University Pl., New York, 10003, United States -73.993515
98      536 E. 5th St., New York, 10009, United States -73.982800
99     245 E. 44th St., New York, 10017, United States -73.971725
100     284 Third Ave., Brooklyn, 11215, United States -73.986150
101  10 Columbus Circle, New York, 10019, United St... -73.982588
102    114 W. 47th St., New York, 10036, United States -73.982864
103   630 Bedford Rd., Tarrytown, 10591, United States -73.829297
104       178 Broadway, Brooklyn, 11211, United States -73.962630
105     31 W. 21st St., New York, 10010, United States -73.992420
106        8 Extra Pl., New York, 10003, United States -73.991606
107    104 E. 30th St., New York, 10016, United States -73.982675
108    344 W. 11th St., New York, 10014, United States -74.008195
109   217 Eldridge St., New York, 10002, United States -73.990135
110      52 Irving Pl., New York, 10003, United States -73.987342
111  610 Lexington Ave., New York, 10022, United St... -73.971277
112     461 Fifth Ave., New York, 10017, United States -73.981575
113      6 W. 28th St., New York, 10001, United States -73.988075
114  10 Columbus Circle, New York, 10019, United St... -73.982340
115       7 Spring St., New York, 10012, United States -73.994410
116      85 Tenth Ave., New York, 10011, United States -74.007700
117   217 Eldridge St., New York, 10002, United States -73.990120
118        70 Pine St., New York, 10005, United States -74.008721
119     239 E. 5th St., New York, 10003, United States -73.989526
120       77 Worth St., New York, 10013, United States -74.005650
121    181 E. 78th St., New York, 10075, United States -73.958275
122  75 Washington Pl., New York, 10011, United States -73.999639
123    125 E. 39th St., New York, 10016, United States -73.978113
124      1170 Broadway, New York, 10001, United States -73.988908
125  265 Elizabeth St., New York, 10012, United States -73.993750
126   169 Thompson St., New York, 10012, United States -74.000460
127  791 Washington Ave., Brooklyn, 11238, United S... -73.962717
128  128 Greenpoint Ave., Brooklyn, 11222, United S... -73.955380
129       149 Broadway, Brooklyn, 11212, United States -73.963170
130        1 Water St., Brooklyn, 11201, United States -73.994298
131  1 Central Park West, New York, 10023, United S... -73.981550
132  240 Central Park South, New York, 10019, Unite... -73.981068
133      261 Moore St., Brooklyn, 11206, United States -73.933687
134     17 W. 20th St., New York, 10011, United States -73.992990
135     2 Harrison St., New York, 10013, United States -74.009110
136  138 Lafayette St., New York, 10013, United States -74.000010
137    175 Second Ave., New York, 10003, United States -73.986466
138     41 W. 42nd St., New York, 10036, United States -73.982025
139     16 W. 22nd St., New York, 10010, United States -73.991463
140     400 Fifth Ave., New York, 10018, United States -73.983570
141    155 W. 51st St., New York, 10019, United States -73.982230
142      7 E. 27th St., New York, 10010, United States -73.987255
143      47 S. 5th St., Brooklyn, 11249, United States -73.966420
144    431 W. 37th St., New York, 10018, United States -73.996500
145      85 Tenth Ave., New York, 10011, United States -74.007714
146     12 E. 12th St., New York, 10003, United States -73.993790
147    239 W. Broadway, New York, 10013, United States -74.005890
148     239 E. 5th St., New York, 10003, United States -73.989227
149   538 Madison Ave., New York, 10022, United States -73.973550
150    138 Orchard St., New York, 10002, United States -73.989220
151    225 Liberty St., New York, 10281, United States -74.015519
152    204 E. 43rd St., New York, 10017, United States -73.973640
153     60 E. 65th St., New York, 10065, United States -73.967504
154    222 E. 39th St., New York, 10158, United States -73.974740
155     42 E. 20th St., New York, 10003, United States -73.988991
156  5-48 49th Ave., Long Island City, 11101, Unite... -73.954281
157     65 E. 55th St., New York, 10022, United States -73.972140
158    23 Commerce St., New York, 10014, United States -74.004510
159  679 Greenwich St., New York, 10014, United States -74.007440
160     5 Madison Ave., New York, 10010, United States -73.987532
161    220 W. 13th St., New York, 10011, United States -74.001370
162   181 Thompson St., New York, 10003, United States -74.000170
163  1015 7th St. NW, Washington, D.C., 20001, Unit... -77.021800
164  1503 17th St. NW, Washington, D.C., 20036, Uni... -77.038340
165  1100 Pennsylvania Ave. NW, Washington, D.C., 2... -77.027010
166  122 Blagden Alley NW, Washington, D.C., 20001,... -77.024594
167  1827 Adams Mill Rd. NW, Washington, D.C., 2000... -77.043020
168  309 Middle St., Washington, D.C., 22747, Unite... -78.159535
169  601 Pennsylvania Ave. NW, Washington, D.C., 20... -77.019910
170  715 8th St. SE, Washington, D.C., 20003, Unite... -76.995140
171  921 Pennsylvania Ave. SE, Washington, D.C., 20... -76.993637
172  1200 16th St. NW, Washington, D.C., 20036, Uni... -77.036771
173  1509 17th St. NW, Washington, D.C., 20036, Uni... -77.038360
174  1340 4th St. NE, Washington, D.C., 20002, Unit... -76.999080
175  1346 Florida Ave. NW, Washington, D.C., 20000,... -77.031050
176  1906 14th St. NW, Washington, D.C., 20000, Uni... -77.032100
177  717 8th St. SE, Washington, D.C., 20003, Unite... -76.995059
178  855 E St. NW, Washington, D.C., 20004, United ... -77.023860
179  1401 Okie St. NE, Washington, D.C., 20002, Uni... -76.984600
180  1015 7th St. NW, Washington, D.C., 20001, Unit... -77.021800
181  1639 S. Wabash Ave., Chicago, 60616, United St... -87.625246
182  953 W. Fulton Market, Chicago, 60607, United S... -87.651881
183  619 W. Randolph St., Chicago, 60661, United St... -87.643560
184  1729 N. Halsted St., Chicago, 60614, United St... -87.648244
185  1723 N. Halsted St., Chicago, 60614, United St... -87.648174
186  3500 N. Elston Ave., Chicago, 60618, United St... -87.706380
187   661 W. Walnut St., Chicago, 60661, United States -87.645130
188  651 W. Washington Blvd., Chicago, 60661, Unite... -87.644611
189  700 N. Sedgwick St., Chicago, 60654, United St... -87.638676
190  4835 N. Western, Unit D, Chicago, 60625, Unite... -87.688736
191  2656 W. Lawrence Ave., Chicago, 60625, United ... -87.695971
192  980 N. Michigan Ave., Chicago, 60611, United S... -87.624290
193  1350 W. Randolph Ave., Chicago, 60607, United ... -87.660860
194  440 S. LaSalle St., Chicago, 60605, United States -87.631813
195      177 N. Ada St., Chicago, 60607, United States -87.660736
196     630 W. Lake St., Chicago, 60661, United States -87.644106
197    445 N. Clark St., Chicago, 60654, United States -87.630969
198     731 W. Lake St., Chicago, 60661, United States -87.646897
199  652 W. Randolph St., Chicago, 60661, United St... -87.644708
200  4710 N. Ravenswood Ave., Chicago, 60640, Unite... -87.674881
201  123 N. Jefferson St., Chicago, 60661, United S... -87.642470
202    2419 W. 14th St., Chicago, 60618, United States -87.686860
203  1466 N. Ashland Ave., Chicago, 60662, United S... -87.667733
204  2610 N. Cannon Dr., Chicago, 60614, United States -87.636212
205  933 N. Ashland Ave., Chicago, 60622, United St... -87.667250

In [111]:
pd.concat([ea_split, ea_list.address], axis = 1)

     lon                                            address
88    NY    458 W. 17th St., New York, 10011, United States
89    NY    212 Greene Ave., Brooklyn, 11238, United States
90    NY      9 W. 53rd St., New York, 10019, United States
91    NY      295 Grand St., New York, 11211, United States
92    NY    73 Thompson St., New York, 10012, United States
93    NY     89 E. 42nd St., New York, 10017, United States
94    NY    11 Madison Ave., New York, 10010, United States
95    NY  47 E. Houston St., New York, 10012, United States
96    NY     381 Lenox Ave., New York, 10027, United States
97    NY  72 University Pl., New York, 10003, United States
98    NY     536 E. 5th St., New York, 10009, United States
99    NY    245 E. 44th St., New York, 10017, United States
100   NY     284 Third Ave., Brooklyn, 11215, United States
101   NY  10 Columbus Circle, New York, 10019, United St...
102   NY    114 W. 47th St., New York, 10036, United States
103   NY   630 Bedford Rd., Tarrytown, 10591, United States
104   NY       178 Broadway, Brooklyn, 11211, United States
105   NY     31 W. 21st St., New York, 10010, United States
106   NY        8 Extra Pl., New York, 10003, United States
107   NY    104 E. 30th St., New York, 10016, United States
108   NY    344 W. 11th St., New York, 10014, United States
109   NY   217 Eldridge St., New York, 10002, United States
110   NY      52 Irving Pl., New York, 10003, United States
111   NY  610 Lexington Ave., New York, 10022, United St...
112   NY     461 Fifth Ave., New York, 10017, United States
113   NY      6 W. 28th St., New York, 10001, United States
114   NY  10 Columbus Circle, New York, 10019, United St...
115   NY       7 Spring St., New York, 10012, United States
116   NY      85 Tenth Ave., New York, 10011, United States
117   NY   217 Eldridge St., New York, 10002, United States
118   NY        70 Pine St., New York, 10005, United States
119   NY     239 E. 5th St., New York, 10003, United States
120   NY       77 Worth St., New York, 10013, United States
121   NY    181 E. 78th St., New York, 10075, United States
122   NY  75 Washington Pl., New York, 10011, United States
123   NY    125 E. 39th St., New York, 10016, United States
124   NY      1170 Broadway, New York, 10001, United States
125   NY  265 Elizabeth St., New York, 10012, United States
126   NY   169 Thompson St., New York, 10012, United States
127   NY  791 Washington Ave., Brooklyn, 11238, United S...
128   NY  128 Greenpoint Ave., Brooklyn, 11222, United S...
129   NY       149 Broadway, Brooklyn, 11212, United States
130   NY        1 Water St., Brooklyn, 11201, United States
131   NY  1 Central Park West, New York, 10023, United S...
132   NY  240 Central Park South, New York, 10019, Unite...
133   NY      261 Moore St., Brooklyn, 11206, United States
134   NY     17 W. 20th St., New York, 10011, United States
135   NY     2 Harrison St., New York, 10013, United States
136   NY  138 Lafayette St., New York, 10013, United States
137   NY    175 Second Ave., New York, 10003, United States
138   NY     41 W. 42nd St., New York, 10036, United States
139   NY     16 W. 22nd St., New York, 10010, United States
140   NY     400 Fifth Ave., New York, 10018, United States
141   NY    155 W. 51st St., New York, 10019, United States
142   NY      7 E. 27th St., New York, 10010, United States
143   NY      47 S. 5th St., Brooklyn, 11249, United States
144   NY    431 W. 37th St., New York, 10018, United States
145   NY      85 Tenth Ave., New York, 10011, United States
146   NY     12 E. 12th St., New York, 10003, United States
147   NY    239 W. Broadway, New York, 10013, United States
148   NY     239 E. 5th St., New York, 10003, United States
149   NY   538 Madison Ave., New York, 10022, United States
150   NY    138 Orchard St., New York, 10002, United States
151   NY    225 Liberty St., New York, 10281, United States
152   NY    204 E. 43rd St., New York, 10017, United States
153   NY     60 E. 65th St., New York, 10065, United States
154   NY    222 E. 39th St., New York, 10158, United States
155   NY     42 E. 20th St., New York, 10003, United States
156   NY  5-48 49th Ave., Long Island City, 11101, Unite...
157   NY     65 E. 55th St., New York, 10022, United States
158   NY    23 Commerce St., New York, 10014, United States
159   NY  679 Greenwich St., New York, 10014, United States
160   NY     5 Madison Ave., New York, 10010, United States
161   NY    220 W. 13th St., New York, 10011, United States
162   NY   181 Thompson St., New York, 10003, United States
163   DC  1015 7th St. NW, Washington, D.C., 20001, Unit...
164   DC  1503 17th St. NW, Washington, D.C., 20036, Uni...
165   DC  1100 Pennsylvania Ave. NW, Washington, D.C., 2...
166   DC  122 Blagden Alley NW, Washington, D.C., 20001,...
167   DC  1827 Adams Mill Rd. NW, Washington, D.C., 2000...
168   DC  309 Middle St., Washington, D.C., 22747, Unite...
169   DC  601 Pennsylvania Ave. NW, Washington, D.C., 20...
170   DC  715 8th St. SE, Washington, D.C., 20003, Unite...
171   DC  921 Pennsylvania Ave. SE, Washington, D.C., 20...
172   DC  1200 16th St. NW, Washington, D.C., 20036, Uni...
173   DC  1509 17th St. NW, Washington, D.C., 20036, Uni...
174   DC  1340 4th St. NE, Washington, D.C., 20002, Unit...
175   DC  1346 Florida Ave. NW, Washington, D.C., 20000,...
176   DC  1906 14th St. NW, Washington, D.C., 20000, Uni...
177   DC  717 8th St. SE, Washington, D.C., 20003, Unite...
178   DC  855 E St. NW, Washington, D.C., 20004, United ...
179   DC  1401 Okie St. NE, Washington, D.C., 20002, Uni...
180   DC  1015 7th St. NW, Washington, D.C., 20001, Unit...
181  CHI  1639 S. Wabash Ave., Chicago, 60616, United St...
182  CHI  953 W. Fulton Market, Chicago, 60607, United S...
183  CHI  619 W. Randolph St., Chicago, 60661, United St...
184  CHI  1729 N. Halsted St., Chicago, 60614, United St...
185  CHI  1723 N. Halsted St., Chicago, 60614, United St...
186  CHI  3500 N. Elston Ave., Chicago, 60618, United St...
187  CHI   661 W. Walnut St., Chicago, 60661, United States
188  CHI  651 W. Washington Blvd., Chicago, 60661, Unite...
189  CHI  700 N. Sedgwick St., Chicago, 60654, United St...
190  CHI  4835 N. Western, Unit D, Chicago, 60625, Unite...
191  CHI  2656 W. Lawrence Ave., Chicago, 60625, United ...
192  CHI  980 N. Michigan Ave., Chicago, 60611, United S...
193  CHI  1350 W. Randolph Ave., Chicago, 60607, United ...
194  CHI  440 S. LaSalle St., Chicago, 60605, United States
195  CHI      177 N. Ada St., Chicago, 60607, United States
196  CHI     630 W. Lake St., Chicago, 60661, United States
197  CHI    445 N. Clark St., Chicago, 60654, United States
198  CHI     731 W. Lake St., Chicago, 60661, United States
199  CHI  652 W. Randolph St., Chicago, 60661, United St...
200  CHI  4710 N. Ravenswood Ave., Chicago, 60640, Unite...
201  CHI  123 N. Jefferson St., Chicago, 60661, United S...
202  CHI    2419 W. 14th St., Chicago, 60618, United States
203  CHI  1466 N. Ashland Ave., Chicago, 60662, United S...
204  CHI  2610 N. Cannon Dr., Chicago, 60614, United States
205  CHI  933 N. Ashland Ave., Chicago, 60622, United St...

In [112]:
region = pd.concat([ca_split, ea_split], axis = 0)
df['region'] = region

In [113]:
set(df['region'])

{'CHI', 'DC', 'NC', 'NY', 'SC'}

In [114]:
df.to_csv('US_Michelin.csv')

# San Francisco

In [20]:
import re

In [21]:
sf_data = df['address'].apply(lambda x: re.search('San Francisco', x))
sf_data = sf_data.apply(lambda x: x if x != None else 0)
sf_index = sf_data[sf_data != 0].index

In [22]:
sf_data = df.loc[sf_index].copy()

In [23]:
sf_data

,name,address,min_price,max_price,currency,cuisine,description,star,comfort,delightful,...,lon,url,country,country_alpha2,continent_code,USD_min_price,USD_max_price,aggregate_cuisine,coast,region
2,Angler,"132 The Embarcadero, San Francisco, 94101, Uni...",75.0,150.0,USD,CONTEMPORARY,Pitched as a more casual counterpart to the st...,1.0,3.0,0.0,...,-122.392130,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,CONTEMPORARY,0,NC
32,Bar Crenn,"3131 Fillmore St., San Francisco, 94101, Unite...",50.0,75.0,USD,FRENCH,It may be located next to Chef Dominique Crenn...,1.0,2.0,0.0,...,-122.435810,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,FRENCH,0,NC
34,Birdsong,"1085 Mission St., San Francisco, 94101, United...",75.0,150.0,USD,AMERICAN,"The front windows are stacked with logs, dried...",1.0,2.0,0.0,...,-122.410480,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,AMERICAN,0,NC
35,Nico,"710 Montgomery St., San Francisco, 94101, Unit...",50.0,75.0,USD,CONTEMPORARY,"After moving to the Financial District, Chef N...",1.0,2.0,0.0,...,-122.403330,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,CONTEMPORARY,0,NC
36,Sorrel,"3228 Sacramento St., San Francisco, 94101, Uni...",50.0,75.0,USD,CALIFORNIAN,"Perched on the edge of Pacific Heights, this s...",1.0,2.0,0.0,...,-122.446140,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,CALIFORNIAN,0,NC
38,Kinjo,"2206 Polk St., San Francisco, 94109, United St...",75.0,150.0,USD,JAPANESE,With Chef/co-owner Billy Kong and consultant c...,1.0,2.0,0.0,...,-122.422005,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,JAPANESE,0,NC
41,In Situ,"151 Third St., San Francisco, 94103, United St...",75.0,150.0,USD,INTERNATIONAL,Like the SF Museum of Modern Art in which it’s...,1.0,2.0,1.0,...,-122.401130,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,FUSION,0,NC
42,Hashiri,"4 Mint Plaza, San Francisco, 94103, United States",75.0,150.0,USD,JAPANESE,This omakase-only sparkler in Mint Plaza may b...,1.0,3.0,0.0,...,-122.407540,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,JAPANESE,0,NC
43,Mister Jiu's,"28 Waverly Pl., San Francisco, 94108, United S...",50.0,75.0,USD,CHINESE,Chef/owner Brandon Jew has brought some of the...,1.0,2.0,0.0,...,-122.406654,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,CHINESE,0,NC
44,jū-ni,"1335 Fulton St., San Francisco, 94117, United ...",75.0,150.0,USD,JAPANESE,"“J?-ni” is Japanese for “twelve,” which also h...",1.0,2.0,0.0,...,-122.438860,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,JAPANESE,0,NC
45,Omakase,"665 Townsend St., San Francisco, 94103, United...",75.0,150.0,USD,JAPANESE,"True, the vibe is friendly and the location is...",1.0,1.0,1.0,...,-122.402980,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,JAPANESE,0,NC
46,Lord Stanley,"2065 Polk St., San Francisco, 94109, United St...",50.0,75.0,USD,CALIFORNIAN,"Like the husband-and-wife team who own it, Lor...",1.0,2.0,0.0,...,-122.422080,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,CALIFORNIAN,0,NC
48,Californios,"3115 22nd St., San Francisco, 94110, United St...",75.0,150.0,USD,MEXICAN,Set in a bohemian area known for its street ta...,2.0,2.0,1.0,...,-122.417145,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,MEXICAN,0,NC
49,Octavia,"1701 Octavia St., San Francisco, 94109, United...",50.0,75.0,USD,CALIFORNIAN,Chef/owner Melissa Perello may already be a lo...,1.0,2.0,0.0,...,-122.427090,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,CALIFORNIAN,0,NC
50,The Progress,"1525 Fillmore St., San Francisco, 94115, Unite...",50.0,75.0,USD,CALIFORNIAN,This is the rare restaurant that guarantees it...,1.0,2.0,0.0,...,-122.432820,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,CALIFORNIAN,0,NC
52,Mourad,"140 New Montgomery St., San Francisco, 94105, ...",50.0,75.0,USD,MOROCCAN,This glamorous outpost at the base of the PacB...,1.0,3.0,0.0,...,-122.399870,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,MEDITERRANEAN,0,NC
53,Lazy Bear,"3416 19th St., San Francisco, 94110, United St...",75.0,150.0,USD,CONTEMPORARY,Communal eating is at the heart of this fine-d...,2.0,2.0,1.0,...,-122.419690,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,CONTEMPORARY,0,NC
54,Al's Place,"1499 Valencia St., San Francisco, 94110, Unite...",25.0,50.0,USD,CALIFORNIAN,Vegetables are the star of the menu at this br...,1.0,2.0,0.0,...,-122.420130,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,25.0,50.0,CALIFORNIAN,0,NC
55,Wako,"211 Clement St., San Francisco, 94118, United ...",75.0,150.0,USD,JAPANESE,Wako blends right in with the sea of Asian res...,1.0,1.0,0.0,...,-122.461525,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,JAPANESE,0,NC
56,Kin Khao,"55 Cyril Magnin St., San Francisco, 94102, Uni...",25.0,50.0,USD,THAI,Tucked into an alcove of the unprepossessing P...,1.0,1.0,0.0,...,-122.409510,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,25.0,50.0,THAI,0,NC
57,Rich Table,"199 Gough St., San Francisco, 94102, United St...",50.0,75.0,USD,CONTEMPORARY,A rustic-chic décor highlighting reclaimed an...,1.0,2.0,0.0,...,-122.422710,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,CONTEMPORARY,0,NC
58,State Bird Provisions,"1529 Fillmore St., San Francisco, 94115, Unite...",25.0,50.0,USD,AMERICAN,"Welcome to the evolution of fine dining, where...",1.0,2.0,0.0,...,-122.432830,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,25.0,50.0,AMERICAN,0,NC
59,Keiko à Nob Hill,"1250 Jones St., San Francisco, 94109, United S...",75.0,150.0,USD,FUSION,"Elegant, discreet and romantic, Keiko à Nob H...",1.0,3.0,0.0,...,-122.414450,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,FUSION,0,NC
60,Benu,"22 Hawthorne St., San Francisco, 94105, United...",75.0,150.0,USD,ASIAN,Benu is an oasis in the heart of the city. The...,3.0,3.0,0.0,...,-122.398760,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,ASIAN,0,NC
61,Atelier Crenn,"3127 Fillmore St., San Francisco, 94123, Unite...",75.0,150.0,USD,CONTEMPORARY,At the hands of accomplished Chef Dominique Cr...,3.0,3.0,0.0,...,-122.435860,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,CONTEMPORARY,0,NC
62,Michael Mina,"252 California St., San Francisco, 94102, Unit...",75.0,150.0,USD,CONTEMPORARY,Power players can't seem to get enough of mega...,1.0,3.0,0.0,...,-122.399574,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,CONTEMPORARY,0,NC
63,Saison,"178 Townsend St., San Francisco, 94107, United...",75.0,150.0,USD,CALIFORNIAN,"Set within an imposing warehouse, this iconic ...",2.0,3.0,1.0,...,-122.392516,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,CALIFORNIAN,0,NC
64,Sons & Daughters,"708 Bush St., San Francisco, 94108, United States",75.0,150.0,USD,CONTEMPORARY,Everyone at this inviting space is warmly prof...,1.0,2.0,0.0,...,-122.409170,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,CONTEMPORARY,0,NC
69,Luce,"888 Howard St., San Francisco, 94103, United S...",50.0,75.0,USD,CONTEMPORARY,"Know that the ambience is pleasant, the space ...",1.0,3.0,0.0,...,-122.404980,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,CONTEMPORARY,0,NC
70,Spruce,"3640 Sacramento St., San Francisco, 94118, Uni...",50.0,75.0,USD,CALIFORNIAN,Set in one of San Francisco’s snazziest neighb...,1.0,2.0,0.0,...,-122.452640,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,CALIFORNIAN,0,NC
71,SPQR,"1911 Fillmore St., San Francisco, 94115, Unite...",50.0,75.0,USD,ITALIAN,Pleasant and homey with excellent modern Itali...,1.0,2.0,0.0,...,-122.433750,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,50.0,75.0,ITALIAN,0,NC
74,Coi,"373 Broadway, San Francisco, 94133, United States",75.0,150.0,USD,CONTEMPORARY,"Warm, neutral tones and a soft, diffused glow ...",2.0,3.0,0.0,...,-122.403310,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,CONTEMPORARY,0,NC
75,Acquerello,"1722 Sacramento St., San Francisco, 94109, Uni...",75.0,150.0,USD,ITALIAN,"With its air of old-world sophistication, Acqu...",2.0,3.0,0.0,...,-122.421310,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,ITALIAN,0,NC
83,Gary Danko,"800 North Point St., San Francisco, 94109, Uni...",75.0,150.0,USD,CONTEMPORARY,The elite meet to eat at this throwback favori...,1.0,3.0,0.0,...,-122.420660,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,CONTEMPORARY,0,NC
84,Quince,"470 Pacific Ave., San Francisco, 94133, United...",75.0,150.0,USD,CONTEMPORARY,An air of refinement touches this dining room—...,3.0,4.0,1.0,...,-122.403370,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,CONTEMPORARY,0,NC
85,Campton Place,"340 Stockton St., San Francisco, 94108, United...",75.0,150.0,USD,INDIAN,The breadth and complexity of Indian cuisine g...,2.0,3.0,0.0,...,-122.406650,https://guide.michelin.com/en/california/san-f...,United States,US,NaN,75.0,150.0,INDIAN,0,NC

In [24]:
sf_data.to_csv('SF_Michelin.csv')

# Chicago